### ISSUE TITLE
Notifications RPC

### ISSUE THREAD

**Issue by relativityboy** [steemit/yo#10]
The clientApp should be able to connect to Yo, identified as a specific user. 
Yo should support JSON-RPC of user-relevant notifications to the clientApp 
---
## Current TODOs for this item
- [x] return modified notifs from mark_* requests
- [x] respect updated_after and other filter options for get_notifications requst
- [x] add settings api
- [ ] figure out auth
- [ ] return real data
- [x] replace the notify_type param with a  notify_types that takes array of types

---

## Requesting notifications - 
* RPC method name `yo.get_notifications`
* RPC parameters (all are optional)
  * created_before=<timestamp> (if it, and 'after' are not present, gets newest 'page' of notifications)
  * updated_after=<timestamp> (all items updated after this time)
  * read=<true|false> (return only those with .read with the corresponding value)
  * type=<one of the notification types> (if not present, does not filter out types)
* *Response*:  a list of notifications order in descending .created value
  * default list size ~30? 
## Marking notifications
The clientApp should be able to send these RPC calls to Yo: 
* RPC method name `yo.mark_read` (set .read true)
* RPC method name `yo.mark_shown` (set .shown true)
* RPC method name `yo.mark_hidden` (set .hide true)
* RPC method name `yo.mark_unread` (set .read false)
* RPC method name `yo.mark_unshown` (set .shown false)
* RPC method name `yo.mark_unhidden` (set .hide false)
* RPC parameters - 
  * ids `{ids:[5, 7, 8, ...]}`
* *Response*  after successfully marking items as read, shown, or hidden (via read, shown, hide properties) Yo returns the list of modified notifications

Notification JSON - this is for a SINGLE notification. A list of these would be present in the response to an rpc call.
```javascript
{
    id: "UID", //needed to track .read
    read: false, //a boolean value
    shown: false, //a boolean value
    hide: false, //a boolean value 
    notificationType: VOTE, //vote, receivedSteem, tagged, resteemed, postComment, commentComment ////this may not be a fully inclusive list. 
        //The current notifications ui mockups suggest types with the following concepts 'total', 'feed', 'reward', 'send', 'mention', 'follow', 'vote', 'comment_reply', 'post_reply', 'account_update', 'message', 'receive'
    created: 'ut timestamp',
    updated: 'ut timestamp', //the last time the notification was modified in yo (think .read, .shown, .hide)
    author:"authorname", //the user that performed the action 
    
    //.data may have multiple formats: 
    
    //for a notification of notificationType:receivedSteem. Not present for other notification types.
    data: {
        amount: 10000.2, //only valid for receivedSteem
    }
    
    //for a notification of notificationType: postComment, commentComment, tagged, vote ////this may not be a fully inclusive list. 
    data:{
        item: { //item is the 'thing that happened' (described by notificationType) usually a comment 
            author: "the item author",
            category: "the item category",
            depth: 0,
            permlink: "the item permlink",
            parentSummary: "",  //a string to summarize the parent item. Title or Content (max 255 chars)
                                //exists only for N_COMMENT_REPLY, N_POST_REPLY,
            summary: "", //a string to summarize the item. Title or Content (max 255 chars)
        },
        rootItem: { //exists only if item.depth > 0, property definitions follow item.*
            author: "",
            category: "",
            permlink: "",
            summary: ""
        }
    }
}
```

**Comment by GarethNelson** [comment]
Please check with @sneak on whether we can use HTTP PUT/POST etc, i'm happy to implement this but the standard policy is to use pure JSON-RPC.

**Comment by sneak** [comment]
This shouldn't be a question anymore.  All of our backend services run via jussi and are JSON-RPC *only*, without any exceptions whatsoever.  That means POST, 100% of the time.

The only things that don't conform to this are the backend service health checks, which have to be GET (we like `/.well-known/healthcheck.json` - but those are handled from the load balancer, never a client app.

This means that there is no server push; clients must make a JSON-RPC periodically to check for new information.

**Comment by sneak** [comment]
I suggest using iso8601 times: eg `2017-09-25T07:11:20Z`

**Comment by GarethNelson** [comment]
There we have it.

I'll implement some get_notifications methods that return unsent/unseen notifications etc.

One comment though: the whole point of Yo is to provide underlying transports (including push), so we will have server push - but it's configured by configuring the transport ahead of time.

**Comment by sneak** [comment]
Yo has two parts to it.

The first part is a block follower, which fires events, which execute various event handlers, which, based on user preferences in the database, send various types of notifications.  One of those types of notifications are "Condenser Notifications" which go into their own table, independent of everything else Yo does (SMS, Email, APNS, Android, whatever else).  This, of course, pushes all sorts of events.

The second part is the JSON-RPC API, accessed by condenser, for reviewing/marking/deleting those Condenser Notifications, and for getting/setting the user's preferences for their event handlers above.  It is this part that we are discussing here - the JSON-RPC calls that condenser will be making to Yo.

**Comment by sneak** [comment]
Note that we will want an admin api that can be accessed with the proper blockchain-based username authentication with a predefined username that allows us to inject arbitrary events into users' Condenser Notifications, for injecting custom notifications of "synthetic" (i.e. non-blockchain) events, such as achievements or sitewide alerts.

**Comment by jnordberg** [comment]
The date format used by steemd is UTC iso8601 minus the Z on the end if we want to standardize on that

**Comment by sneak** [comment]
That works for me.  Our parsers should accept it with or without the Z, to conform to spec.  Ideally steemd would return them with the Z.

**Comment by sneak** [comment]
Implementation note: Yo should periodically prune its Condenser Notifications table of anything more than 14 days old, assuming that all users' notifications go into a single table, to ensure that the table doesn't grow too large.  Notifications are ultimately ephemeral and do not need to live forever, even unread.

**Comment by GarethNelson** [comment]
Got it, for admin interface that can be an entirely separate app that simply talks to the same DB and uses the API.

**Comment by sneak** [comment]
No, keep it in the same app - just add another RPC method.  We'll authenticate it the same way as the other calls from clients, but with a blockchain username that is passed in with an environment variable.

**Comment by GarethNelson** [comment]
I meant for the UI, my thinking was to have another app that isn't integrated into the same daemon process but still talks to yo's API and manipulates the same backend DB.

**Comment by relativityboy** [comment]
I've updated the doc to include two additional calls *mark as shown*, and  *hide* with respective new properties on the object.

PUT was more about expected behavior. RPC ftw.

**Comment by sneak** [comment]
I imagine our UI for a lot of these admin/backend RPC actions is going to be `curl` for the foreseeable future. :)

**Comment by bnchdrff** [comment]
a few additional calls, taking `ids` list as a param:

* RPC method name `yo.set_notifications_unread` (set .read false)
* RPC method name `yo.set_noficiations_unshown` (set .shown false)
* RPC method name `yo.set_notifications_unhidden` (set .hide false) (not using this in the frontend yet but we probably will want to sooner or later!)

**Comment by GarethNelson** [comment]
```
Sending:
{'id': 1,
 'jsonrpc': '2.0',
 'method': 'yo.get_notifications',
 'params': {'test': True, 'username': 'test_user'}}
Response headers:
{'Date': 'Tue, 10 Oct 2017 19:42:19 GMT', 'Content-Length': '1473', 'Content-Type': 'application/json; charset=utf-8', 'Server': 'Python/3.6 aiohttp/2.2.5'}
Response JSON:
{u'id': 1,
 u'jsonrpc': u'2.0',
 u'result': [{u'created': u'2017-10-10T21:41:26.504400',
              u'data': {u'amount': 6.66},
              u'notify_id': 899505,
              u'notify_type': u'power_down',
              u'read': False,
              u'seen': False,
              u'updated': u'2017-10-10T21:41:26.504400',
              u'username': u'test_user'},
             {u'created': u'2017-10-10T21:41:26.504414',
              u'data': {u'amount': 13.37},
              u'notify_id': 4943982,
              u'notify_type': u'power_up',
              u'read': False,
              u'seen': False,
              u'updated': u'2017-10-10T21:41:26.504414',
              u'username': u'test_user'},
             {u'created': u'2017-10-10T21:41:26.504421',
              u'data': {u'resteemed_item': {u'author': u'test_user',
                                            u'category': u'test',
                                            u'permlink': u'test-post',
                                            u'resteemed_by': u'some_user',
                                            u'summary': u'A test post'}},
              u'notify_id': 7188138,
              u'notify_type': u'resteem',
              u'read': False,
              u'seen': False,
              u'updated': u'2017-10-10T21:41:26.504421',
              u'username': u'test_user'},
             {u'created': u'2017-10-10T21:41:26.504426',
              u'data': {u'item': {u'author': u'some_user',
                                  u'category': u'test',
                                  u'permlink': u'another-test',
                                  u'summary': u'Stuff etc'}},
              u'notify_id': 2056410,
              u'notify_type': u'feed',
              u'read': False,
              u'seen': False,
              u'updated': u'2017-10-10T21:41:26.504426',
              u'username': u'test_user'},
             {u'created': u'2017-10-10T21:41:26.504431',
              u'data': {u'amount': {u'SBD': 6.66, u'SP': 13.37},
                        u'item': {u'author': u'test_user',
                                  u'category': u'test',
                                  u'permlink': u'test-post',
                                  u'summary': u'A test post'},
                        u'reward_type': u'curation'},
              u'notify_id': 7647424,
              u'notify_type': u'reward',
              u'read': False,
              u'seen': False,
              u'updated': u'2017-10-10T21:41:26.504431',
              u'username': u'test_user'}]}
```

**Comment by bnchdrff** [comment]
two requests:

1) i'd like to request once and receive any notificiations that were created after or updated since a given timestamp -- this will be handy for polling so we can capture any new or modified notifications without having to run two types of requests, i.e. a special param `created_or_updated_after`

2) can the response include meta info about the requested cursor & the total number of results available? this would save requests, specifically in the case of the polling requests -- for example, we'll ideally set the limit on those requests to minimize the likliehood of having to do more than one request, and it'd be helpful to know that we do not have to request the next page.

**Comment by relativityboy** [comment]
@GarethNelson - the general structure looks good with the following caveats
1. the `resteem_item` attribute should just be `item`
1. `username` at the root should be `author` (I get your thought there, but *reasons*)
2. there are no examples of `rootItem` in the response.

The json spec in the main description is exactly what we're looking for in terms of attr names and structure. It's based off comment responses returned by the api. It'll be more familiar to devs coming in and out of different parts of the codebase.

**Comment by GarethNelson** [comment]
1 - resteemed_item i named that way for a specific reason, because the fields are slightly different in plain old "item", might map better to objects

2 - username is the same in all cases, author doesn't make sense for things like money transfers

3 - this will come in next update, i'll let you know

**Comment by relativityboy** [comment]
1. Ah! So, we actually need the structure to be the same, all types of notification elements are built with a single view component that relies on them being identical (except for very special cases like receive steem). [We actually have the UI built out and working on mock data](https://github.com/steemit/condenser/blob/notification-ui/src/app/components/elements/notification/_TestData.js)
1. author is conceptually better in this case, since the user who performed the action that triggered the notification could be considered the "author" of the notification. This also holds for "item.author" and "rootItem.author". (those are the authors of item & rootItem respectively)
1. sweet.

**Comment by GarethNelson** [comment]
1 - i'll reorganise this to be the same

2 - to make it clear: the API takes "username" as "notifications relevant to this user", whereas "author" would mean the author of a piece of content - doing otherwise and using "author" for everything would confuse matters greatly. In the case of item and root_item data of course, author makes total sense.

3. Watch this space :)

**Comment by relativityboy** [comment]
TODOs for this item
- [ ] return modified notifs from mark_* requests
- [ ] respect updated_after and other filter options for get_notifications requst
- [ ] add settings api
- [ ] figure out auth
- [ ] return real data

**Comment by bnchdrff** [comment]
another request: instead of `notify_type` param, accept `notify_types` as an array of types to filter

**Comment by john-g-g** [comment]
@relativityboy @GarethNelson @bnchdrff I think this is resolved (other than auth which has its own issue). Anybody disagree?

**Comment by GarethNelson** [comment]
This was more of a toplevel issue to track implementing the API - i'd call it closed, but @relativityboy can comment on anything missing.
