### ISSUE TITLE
service flapping, check logs

### ISSUE THREAD

**Issue by sneak** [steemit/yo#11]
<img width="667" alt="screen shot 2017-09-26 at 03 01 52" src="https://user-images.githubusercontent.com/408977/30846840-1f7e158c-a267-11e7-957c-e24fa1622346.png">

**Comment by sneak** [comment]
(looks like SBDS was affected too, so it could have been a `steemd` hiccup - but steemd should probably have to be down for >120s to make yo or sbds fail health checks.)

**Comment by GarethNelson** [comment]
Issue is in fact due to not getting anything back from steemd as seen in the logs, an exception is thrown because it returns None.

We need to get jussi stable to make this work properly.

**Comment by GarethNelson** [comment]
This was fixed quite a while back (by automatically retrying on failure), closing issue
