### ISSUE TITLE
Implement blockchain follower coordination in database

### ISSUE THREAD

**Issue by GarethNelson** [steemit/yo#111]
As discussed in meeting, we should have a DB table for blockchain followers to coordinate across instances so we're not repeating work.

Only 1 should be active at a time, with others simply observing and only kicking in if it looks like the primary has crashed etc.

**Comment by GarethNelson** [comment]
I am unable to unassign myself from these issues

@john-g-g @sneak unless I am rehired at steemit, please unassign any issues from me.

**Comment by GarethNelson** [comment]
Since I am unable to unassign myself from this issue, i'm closing it instead.

Do not assume the issue is actually resolved, I suggest re-opening it and making sure someone who still works at steemit is assigned the issue.

I would be open however to licensing my changes which implemented all the issues mentioned in #113 to Steemit Inc as a one-off (ned can email me to arrange this - i'll just charge my old hourly rate), or you can wait until I release my fork of yo under a free license.

**Comment by sneak** [comment]
@GarethNelson - please do not modify issues in our repos.
