### ISSUE TITLE
Require email templates

### ISSUE THREAD

**Issue by GarethNelson** [steemit/yo#14]
We need email templates for each possible notification type, they should be provided as plain text or HTML documents with placeholder values.

**Comment by plink01001** [comment]
For the email templates, is there an easy way to embed a post preview (similar to what is shown on the trending page or a feed) in the context of the notification email?

Example:
@steemitblog - you have a new reply to your post:
![image](https://user-images.githubusercontent.com/31787860/31474586-5868aee6-aec1-11e7-80c0-87cd53a07b1e.png)

**Comment by GarethNelson** [comment]
As discussed earlier, yes - that is doable

**Comment by plink01001** [comment]
Is this the list of notifications that we need email templates for?

Security
– account_update 
– power_down
My posts
- vote
– comment_reply 
– post_reply
Wallet 
– receive
– send 
– reward
Mentions
– mention
Followers
– follow
New posts
- feed

**Comment by plink01001** [comment]
For the "My Posts" "vote" notification type, are there only notifications for votes on posts, or will the same notification event be triggered if there is a vote on a comment?

**Comment by plink01001** [comment]
From pon regarding reward notifications: It would be nice to provide context on why they got a reward. For example, 'You earned an author reward of xx tokens for your post {blog title}'. Or, 'You earned a curation reward of xx tokens for upvoting {blog title}. Do we have access to this info?

**Comment by GarethNelson** [comment]
Closing this issue after discussion on slack and resulting google doc
