### ISSUE TITLE
Notification ids should be Integers for both output and input

### ISSUE THREAD

**Issue by relativityboy** [steemit/yo#16]
Currently yo transmits ids as strings, but accepts only integers.

The api should have a consistent type for ids in all calls. (ease of api development)

**Comment by GarethNelson** [comment]
Which call is returning strings? I am unable to reproduce this.

An example returned notification from yo.get_notifications:
`
{
         "notify_type" : "vote",
         "data" : {
            "author" : "some_other_user",
            "weight" : 100,
            "item" : {
               "permlink" : "test-post-29",
               "depth" : 0,
               "author" : "test_user",
               "category" : "test",
               "summary" : "A test post"
            }
         },
         "seen" : false,
         "created" : "2017-10-18T19:41:24.329996",
         "username" : "test_user",
         "notify_id" : 29,
         "read" : false,
         "updated" : "2017-10-18T19:41:24.329996"
      }

`

**Comment by GarethNelson** [comment]
As discussed on slack, not a current issue
