### ISSUE TITLE
Mysql database connection string incorrect format for sqlalchemy

### ISSUE THREAD

**Issue by john-g-g** [steemit/yo#22]
https://github.com/steemit/yo/blob/46f21265d85714091d136128f48521a310d05f86/yo/db.py#L89
For mysql with their utf8 support use this format:

`dialect+driver://username:password@host:port/database?charset=utf8mb4`

Make sure our driver supports server-side cursors, its specified here if you aren't sure:
http://docs.sqlalchemy.org/en/latest/dialects/mysql.html

**Comment by GarethNelson** [comment]
The format in use is actually required by the driver currently in use, using the format you have specified here results in it not connecting to custom server IP+port, as silly as that sounds.

It sounds hacky I know, but my proposal is to simply parse the environment variable DB_URL or similar given in the standard format and to then apply the pymysql-specific hack by reconstructing the URL in the format it is currently in.

**Comment by sneak** [comment]
Don't parse it, just pass it in in the single string format that the driver requires.  Time is of the essence.

**Comment by GarethNelson** [comment]
That's simple enough so long as it's clear it needs to use this weird format for now, so whatever RDS provides might need manual tweaking

**Comment by GarethNelson** [comment]
As of now this seems to work with preconstructed URLs in the migrate_mock_api branch

**Comment by john-g-g** [comment]
If this isn't a problem, then you're free to close it @GarethNelson

**Comment by GarethNelson** [comment]
Closing as it's no longer a current issue

**Comment by john-g-g** [comment]
where are you passing the `charset=utf8mb4` parameter to the client?

**Comment by GarethNelson** [comment]
That can be added as an option like an HTTP URL like the one specified above:

dialect+driver://username:password@host:port/database?charset=utf8mb4

Adding charset to the URL is a deploy issue, it should "just work" if the correct config is setup when deploying.
