### ISSUE TITLE
A ‘reset-statuses’ api call would be very helpful

### ISSUE THREAD

**Issue by john-g-g** [steemit/yo#44]
A ‘reset-statuses’ api call that resets ‘read’, ‘shown’, ‘hide’ for all notifications for a userwould be very helpful

Example RPC call
```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "yo.reset_statuses",
    "params": {
      "username": "test_user"
    }
}
```

It does not need to return the reset notifications.

**Comment by relativityboy** [comment]
Added priority/high because will help very much when debugging condenser. This has _immediate_ payoff.

**Comment by GarethNelson** [comment]
What values should they be reset to? Unseen/Unshown?

Please clarify and this can be done fairly trivially

**Comment by bnchdrff** [comment]
unshown / unread / unhidden would be fantastic

**Comment by relativityboy** [comment]
They all start with value of `false`, so probably that would be the value to _reset_ them to.
