### ISSUE TITLE
Issues not filed as issues

### ISSUE THREAD

**Issue by john-g-g** [steemit/yo#45]
@GarethNelson  Please file anything in the [TODO](https://github.com/steemit/yo/blob/7b7a1443a6a21272198b038ca908c9447a63137a/TODO) as an issue and then remove this file from the repo

**Comment by jnordberg** [comment]
Yo, I heard you like issues so I made an issue about your issues

**Comment by GarethNelson** [comment]
Some of the stuff listed in that TODO is no longer relevant, and most of it is already in place (the little asterisk is my way of marking it as done), but none of it is urgent so i'll make this a low priority and review later.

I don't believe anything listed in that file is needed for MVP, it's mainly stuff for longterm scaling, VAPID (not currently supported) and some refactoring/stylistic issues, so i've removed that milestone.

**Comment by GarethNelson** [comment]
Closing this issue to keep stuff clean, we can revisit VAPID later and the rest is just style issues etc.
