### ISSUE TITLE
current config uses sqlite in dev beanstalk env

### ISSUE THREAD

**Issue by john-g-g** [steemit/yo#46]

**Comment by john-g-g** [comment]
This happens even when `YO_DB_URL` is defined

```INFO:yo.db:Using sqlite engine for database storage```

**Comment by GarethNelson** [comment]
Fix in PR:
https://github.com/steemit/yo/pull/38

Please review and merge

**Comment by GarethNelson** [comment]
Closing this as it appears fixed, if i'm incorrect please reopen or file a new issue

**Comment by john-g-g** [comment]
still not working: `INFO:yo.db:Using sqlite engine for database storage``

**Comment by john-g-g** [comment]
Only use `DB_URL`
The goal is that sqlite is only used in EB if someone explicitly sets the `DB_URL` to sqlite://:memory: It should never happen if an env var is unset or set with a typo. 
This means removing the `sqlite` and `mysql` sections from `yo.cfg`
