### ISSUE TITLE
replace `seen` with `shown` in JSONRPC structures and api call strings.

### ISSUE THREAD

**Issue by relativityboy** [steemit/yo#48]
The specification in https://github.com/steemit/yo/issues/10 asks for 'shown' for both the notification attribute name, and for the end of the api call names.

`yo.mark_shown`
`yo.mark_unshown`
```
//attribute location in list of notifications
[
  {
    shown:false
  }
]
```

**Comment by jnordberg** [comment]
Cleared the assignees, let's only assign when we have someone that takes ownership of the issue so we can keep track of who's doing what

**Comment by jnordberg** [comment]
Had a look at this now, can we change the spec to say `seen`/`unseen`? It's already implemented everywhere as that

**Comment by bnchdrff** [comment]
changing consumer to use seen/unseen https://github.com/steemit/condenser/issues/1867

this issue can be closed now

**Comment by GarethNelson** [comment]
Closing as per above

**Comment by relativityboy** [comment]
This is the wrong naming choice, but will go with it as condenser appears to have more bandwidth right now.

:(

**Comment by relativityboy** [comment]
@jnordberg @GarethNelson - is there an issue in condenser to track this change?

**Comment by relativityboy** [comment]
After reviewing the condenser codebase I’m feeling pretty bad about closing this. Condenser has a standard *shown* for all other aspects of the UI. It’s more accurate, and it conforms to the _actual_ api spec we put out at the beginning. 

If this is a matter of a regex replacement. We should do it.

**Comment by GarethNelson** [comment]
@relativityboy as discussed earlier, @john-g-g is now doing this in master branch, please review his changes and confirm they work for you when you reclose this issue.
