### ISSUE TITLE
get_notifications should respect notify_types and username

### ISSUE THREAD

**Issue by bnchdrff** [steemit/yo#49]
as an api consumer, when i make a request like this:

```json
{
  "jsonrpc":"2.0",
  "id":1,
  "method":"yo.get_notifications",
  "params":{
    "username":"money",
    "notify_types": ["comment_reply", "post_reply", "vote", "resteem"]
  }
}
```

i expect the reply to contain notifications that are of any of those types, excluding notifications that don't have those types.

i also expect the reply to only contain notifications relevant to the provided username.

**Comment by GarethNelson** [comment]
Is that a literal copy/paste of the request? Because there's a typo in notify_types.

If this is working now please close the issue.

**Comment by bnchdrff** [comment]
yes, that's a typo. i'll correct it. i am unable to test whether or not it is working because dev is down. the issue is here to make sure this requirement is met.

**Comment by GarethNelson** [comment]
I have previously verified this works myself and it should still be working in master right now so i'm closing the issue. Please reopen it if it turns out it is not fixed.
