### ISSUE TITLE
Testing methods and data belong in tests

### ISSUE THREAD

**Issue by john-g-g** [steemit/yo#50]
https://github.com/steemit/yo/blob/7b7a1443a6a21272198b038ca908c9447a63137a/yo/api_server.py#L138

https://github.com/steemit/yo/blob/7b7a1443a6a21272198b038ca908c9447a63137a/yo/api_server.py#L143

**Comment by GarethNelson** [comment]
The test_method can go away, but reset_test_data is part of the mock data API and needs to remain in place at least until we go to prod, and even then we might want to keep it for testing outside apps against.

It can be disabled for security reasons using an environment variable or in yo.cfg.
